---

# Install group spicer        
- name: Install group spicer
  group: name=spicer state=present gid={{ spicer_gid }}

# Install group deploy        
- name: Install group deploy 
  group: name=deploy  state=present gid={{ deploy_gid }}

# Install group www-data        
- name: Install group www-data 
  group: name=www-data state=present gid=33

# Install group docker        
- name: Install group docker
  group: name=docker  state=present 

# Install User Spicer
- name: Install user spicer.
  user: name=spicer state=present home=/home/spicer shell=/bin/bash group=spicer groups=sudo,root,docker,www-data,deploy append=yes uid={{ spicer_uid }}
  
# Install User Deploy
- name: Install user deploy.
  user: name=deploy state=present home=/home/deploy shell=/bin/bash group=deploy groups=docker append=yes uid={{ deploy_uid }}

# Set the ssh directory - spicer
- name: Set the .ssh directory for spicer.
  file: path=/home/spicer/.ssh state=directory owner=spicer group=spicer mode=0700

# Set the ssh directory - deploy
- name: Set the .ssh directory for deploy.
  file: path=/home/deploy/.ssh state=directory owner=deploy group=deploy mode=0700

# Install authorized_keys - spicer
- name: Add authorized_keys For Spicer
  copy: src=authorized_keys.spicer dest=/home/spicer/.ssh/authorized_keys2 owner=spicer group=spicer
 
# Install authorized_keys - deploy
- name: Add authorized_keys For deploy
  copy: src=authorized_keys.deploy dest=/home/deploy/.ssh/authorized_keys2 owner=deploy group=deploy 
  
# Install a fancy bashrc - spicer
- name: Install a fancy bashrc - spicer
  copy: src=bash_login.spicer dest=/home/spicer/.bash_login mode=0600 owner=spicer group=spicer
  
# Linode installs this on bootstrap
- name: Removing /home/spicer/.ssh/authorized_keys
  file: path=/home/spicer/.ssh/authorized_keys state=absent
  
# Disable spicer password
- name: Disabled spicer password
  command: passwd -d spicer   
  
# Disable deploy password
- name: Disabled deploy password
  command: passwd -d deploy   