#!/bin/bash

# Date: 3/5/2017
# Author(s): Spicer Matthews (spicer@options.cafe)
# Copyright: 2018 Cloudmanic Labs, LLC. All rights reserved.
#
# Run all tests. We do this instead of test ./... because lots of tests are broken. We should do away
# with this once all tests work. (Also note there might be issues with parrel tests all connecting to mysql)
#
# Note: CI runs these tests too. Also need to make sure Github Secrets has proper keys
#

# exit when any command fails
set -e

# CD into the root directory
cd ../

# Run all tests
go test ./library/cache/...
go test ./library/analyze/...
go test ./library/checkmail/...
go test ./library/helpers/...
go test ./library/market/...
go test ./library/realip/...
go test ./brokers/pull/...
go test ./models/...
go test ./backtesting/...
# go test ./controllers/...
# go test ./library/reports/...
# go test ./library/services/...
# go test ./library/archive/...
# go test ./brokers/eod/...
# go test ./brokers/tradier/...

# CD back into the script directory
cd scripts
