# {{ ansible_managed }}

version: '2.1'

services:

  # App
  app:
           
    hostname: app.options.cafe

    container_name: app.options.cafe
    
    ports:
      - "80:7652"     
      - "443:7653"           

    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        P_UID: 1002
        P_GID: 1002       
    
    image: app.options.cafe/golang:1.8.1-alpine           

    restart: always
    
    environment:   
      VIRTUAL_HOST: app.options.cafe 
                      
    networks:
      - shared 
  
networks:
  shared:
    external:
      name: shared 