# {{ ansible_managed }}

version: '2.1'

services:

  # App
  app:
           
    hostname: app.options.cafe

    container_name: app.options.cafe         

    ports:
      - "80:7080"
      - "443:7043"

    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        P_UID: 1002
        P_GID: 1002     
    
    image: app.options.cafe/golang:1.8.1-alpine

    logging:
      driver: "syslog"
      options:
        syslog-address: tcp+tls://logs6.papertrailapp.com:49242
        tag: app.options.cafe

    volumes:
      - ../cache:/cache:rw
      - ../letsencrypt:/letsencrypt:rw 

    environment:
      VIRTUAL_HOST: app.options.cafe
      LETSENCRYPT_HOST: app.options.cafe
      LETSENCRYPT_EMAIL: help@options.cafe                     

    restart: always
    
    env_file:
      - .env      
                      
    networks:
      - shared 

  # Cron
  cron:
           
    hostname: cron.options.cafe

    container_name: cron.options.cafe
    
    build:
      context: ./build
      dockerfile: Dockerfile-cron
      args:
        P_UID: 1002
        P_GID: 1002      
    
    image: cron.options.cafe/golang:1.8.1-alpine           

    logging:
      driver: "syslog"
      options:
        syslog-address: tcp+tls://logs6.papertrailapp.com:49242
        tag: cron.options.cafe

    volumes:
      - ../cache:/cache:rw

    restart: always
    
    env_file:
      - .env      
                      
    networks:
      - shared       
  
networks:
  shared:
    external:
      name: shared 