---

# Setup app.options.cafe base directory
- name: Setup app.options.cafe base directory
  file: path={{ app_site_dir }}/app.options.cafe owner=optionscafe group=optionscafe mode=0755 state=directory

# Create docker directory
- name: Create docker directory
  file: path={{ app_site_dir }}/app.options.cafe/docker owner=optionscafe group=optionscafe mode=0755 state=directory

# Create docker build directory
- name: Create docker build directory
  file: path={{ app_site_dir }}/app.options.cafe/docker/build owner=optionscafe group=optionscafe mode=0755 state=directory

# Create cache directory
- name: Create cache directory
  file: path={{ app_site_dir }}/app.options.cafe/cache owner=optionscafe group=optionscafe mode=0755 state=directory

# Install docker-compose
- name: Install docker-compose
  template: src=docker-compose.yml dest={{ app_site_dir }}/app.options.cafe/docker/docker-compose.yml owner=optionscafe group=optionscafe mode=0644

# Install Dockerfile
- name: Install Dockerfile
  template: src=Dockerfile dest={{ app_site_dir }}/app.options.cafe/docker/build/Dockerfile owner=optionscafe group=optionscafe mode=0644

# Install ENV File
- name: Install ENV File
  template: src=env dest={{ app_site_dir }}/app.options.cafe/docker/.env owner=optionscafe group=optionscafe mode=0644

# See if we have uploaded the binary for options cafe yet.
- name: Register {{ app_site_dir }}/app.options.cafe/docker/build/app.options.cafe
  stat: path=/etc/shorewall/rules
  register: app_binary

# Pull docker
- name: Building image for {{ app_site_dir }}/app.options.cafe/docker
  command: docker-compose build
  when: app_binary.stat.exists == True
  args:
    chdir: "{{ app_site_dir }}/app.options.cafe/docker"

# Stop docker
- name: Stopping docker container for {{ app_site_dir }}/app.options.cafe/docker
  command: docker-compose down --remove-orphans 
  when: app_binary.stat.exists == True  
  args:
    chdir: "{{ app_site_dir }}/app.options.cafe/docker"

# Start docker
- name: Starting docker for {{ app_site_dir }}/app.options.cafe/docker
  command: docker-compose up -d
  when: app_binary.stat.exists == True  
  args:
    chdir: "{{ app_site_dir }}/app.options.cafe/docker"