---

# Setup app.options.cafe base directory
- name: Setup app.options.cafe base directory
  file: path=/sites/optionscafe/app.options.cafe owner=optionscafe group=optionscafe mode=0755 state=directory

# Create docker directory
- name: Create docker directory
  file: path=/sites/optionscafe/app.options.cafe/docker owner=optionscafe group=optionscafe mode=0755 state=directory

# Create docker build directory
- name: Create docker build directory
  file: path=/sites/optionscafe/app.options.cafe/docker/build owner=optionscafe group=optionscafe mode=0755 state=directory

# Install app.options.cafe binary
- name: Copying app.options.cafe binary to server(s)
  copy: src=../backend/builds/app.options.cafe dest=/sites/optionscafe/app.options.cafe/docker/build owner=optionscafe group=optionscafe mode=0755  

# Install docker-compose
- name: Install docker-compose
  template: src=app-docker-compose.yml dest=/sites/optionscafe/app.options.cafe/docker/docker-compose.yml owner=optionscafe group=optionscafe mode=0644

# Install Dockerfile
- name: Install Dockerfile
  template: src=app-Dockerfile dest=/sites/optionscafe/app.options.cafe/docker/build/Dockerfile owner=optionscafe group=optionscafe mode=0644