---

# See if we have uploaded the binary for options cafe yet.
- name: Register {{ app_site_dir }}/app.options.cafe/docker/build/app.options.cafe
  stat: path={{ app_site_dir }}/app.options.cafe/docker/build/app.options.cafe
  register: app_binary

# Pull docker
- name: Building image for {{ app_site_dir }}/app.options.cafe/docker
  command: docker-compose build
  become: yes
  become_user: deploy
  when: app_binary.stat.exists == True
  args:
    chdir: "{{ app_site_dir }}/app.options.cafe/docker"

# Stop docker
- name: Stopping docker container for {{ app_site_dir }}/app.options.cafe/docker
  command: docker-compose down --remove-orphans 
  become: yes
  become_user: deploy  
  when: app_binary.stat.exists == True  
  args:
    chdir: "{{ app_site_dir }}/app.options.cafe/docker"

# Start docker
- name: Starting docker for {{ app_site_dir }}/app.options.cafe/docker
  command: docker-compose up -d
  become: yes
  become_user: deploy  
  when: app_binary.stat.exists == True  
  args:
    chdir: "{{ app_site_dir }}/app.options.cafe/docker"