---

- name: Deploy app.options.cafe to production
  
  hosts: production
  
  become: yes
  
  become_user: optionscafe

  roles:
    - app
    - app-restart    
    
  vars_files:
    - "vars/env.yml"
    - "vars/all.yml"    
