---

- name: Deploys the server config for app.options.cafe to production
  
  hosts: production

  become: yes
  
  become_user: root

  roles:
    - bootstrap
    - users
    - docker-sites
    - docker-mysql            
    - app-config
    
  vars_files:
    - "vars/env.yml"
    - "vars/all.yml"