name: Backend CI
on: push

jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.17.6'
      
      - name: Install Go modules
        run: |
          cd backend
          go mod tidy
          ls -lh
          pwd
          ls -lha $HOME

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: go_modules-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go_modules-

  Build:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.17.6'

      - name: Load Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: go_modules-${{ hashFiles('**/go.sum') }}

      - name: Print Go Version
        run: go version

      - name: Step
        run: echo ${{ github.sha }}

      - name: Build Backend
        run: |
          cd backend
          env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o builds/app.options.cafe